version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=
      - PORT=5001
      - JWT_SECRET=
      - JWT_REFRESH_SECRET=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=
      - APP_URL=
